spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    #spring:
  #datasource:
    #url: jdbc:h2:mem:testdb
    initialization-mode: always
    sql-script-encoding: utf-8

    properties:
      hibernate:
        format_sql: false

    show-sql: true
