spring:
  application:
    name: gateway
  config:
    activate:
      on-profile: dev
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
      - id: admin_server_route
        uri: lb://admin-server
        predicates:
        - Path=/admin-server/**
        filters:
        - StripPrefix=1
      - id: service-advertisement
        uri: lb://service-advertisement
        predicates:
        - Path=/service-advertisement/**
        filters:
        - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true    
management:
  endpoints:
    web:
      exposure:
        include: "*"
server.port: 7777