debug: true
spring:
  application:
    name: service-advertisement
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    initialization-mode: never
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true
logging:
  file:
    name: log/service-advertisement.log
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 0