version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - nw
    hostname: "spring18db"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://spring18db:5432/db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    privileged: true
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - nw
networks:
  nw: