spring:
  batch:
    job:
      enabled: true
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      database: spring-14
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.sokolovee.spring14.mongock.changelog
