spring:
  application:
    name: service-advertisement
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true
logging:
  file:
    name: log/service-advertisement.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0