CREATE TABLE ADVERTISEMENT(
    ID NUMBER(10,0) PRIMARY KEY,
    SUBJECT VARCHAR(512),
    BODY VARCHAR(4096),
    OWNER_ID NUMBER(10,0),
    CREATE_DATE_TIME TIMESTAMP WITH LOCAL TIMEZONE_LOCAL,
    IS_ACTIVE VARCHAR(1)
);

CREATE TABLE PERSON(
    ID NUMBER(10,0) PRIMARY KEY,
    USERNAME VARCHAR(50)  NOT NULL,
    FULL_NAME VARCHAR(512),
);

CREATE TABLE USER(
    USERNAME VARCHAR(50)  NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ENABLED  VARCHAR(1)   NOT NULL DEFAULT 1,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE CONTACT(
    ID NUMBER(10,0) PRIMARY KEY,
    TYPE VARCHAR(512),
    CONTENT VARCHAR(512),
    COMMENT VARCHAR(1028),
    PERSON_ID NUMBER(10,0)
);

ALTER TABLE ADVERTISEMENT
ADD CONSTRAINT FK_ADVERTISEMENT_PERSON FOREIGN KEY (OWNER_ID)
REFERENCES PERSON (ID);

ALTER TABLE CONTACT
ADD CONSTRAINT FK_CONTACT_PERSON FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID);

--CREATE TABLE users
--(
--    username VARCHAR(50)  NOT NULL,
--    password VARCHAR(100) NOT NULL,
--    enabled  TINYINT      NOT NULL DEFAULT 1,
--    PRIMARY KEY (username)
--);

CREATE TABLE authorities
(
    username  VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    FOREIGN KEY (username) REFERENCES person (username)
);

CREATE UNIQUE INDEX ix_auth_username
    on authorities (username, authority);