CREATE TABLE AUTHOR
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOK
(
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT
);

CREATE TABLE GENRE
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

ALTER TABLE BOOK
    ADD CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHOR (ID)
;
ALTER TABLE BOOK
    ADD CONSTRAINT FK_BOOK_GENRE FOREIGN KEY (GENRE_ID)
        REFERENCES GENRE (ID)
;