
CREATE TABLE AUTHOR(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOK(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT
);

CREATE TABLE GENRE(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);
