spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        native:
          search-locations: file:./configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server.port: 8888